services:
#    perfico_dosales.example:
#        class: Perfico\DosalesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    perfico_dosales.call.manager:
        class: Perfico\DosalesBundle\Service\CallManager
        arguments:
            - @doctrine.orm.entity_manager

    perfico_dosales.pbx_event_manager:
        class: Perfico\DosalesBundle\Service\PBXEventManager
        arguments:
            - @doctrine.orm.entity_manager
            - @core.manager.client
            - @core.manager.user
            - @translator.default